# Generated by Django 3.2.17 on 2023-03-31 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0014_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 2, 8, 40, 962530)),
        ),
        migrations.AddField(
            model_name='order',
            name='numTickets',
            field=models.IntegerField(default=1),
        ),
    ]
