# Generated by Django 3.2.17 on 2023-04-02 20:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('odyssey', '0017_auto_20230402_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 20, 54, 0, 236141)),
        ),
    ]
