# Generated by Django 3.2.17 on 2023-04-03 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0020_alter_order_depart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='depart_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 17, 27, 54, 313910)),
        ),
    ]
