# Generated by Django 3.2.17 on 2023-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odyssey', '0023_alter_order_depart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='depart_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
